# mornitoring/prometheus.yml

global:
  scrape_interval: 15s     # 기본 스크래핑 간격
  evaluation_interval: 15s # 알림 규칙 평가 간격
  scrape_timeout: 10s      # 스크래핑 타임아웃

# 알림 관리자 (선택사항)
alerting:
  alertmanagers:
  - static_configs:
    - targets:
      # - alertmanager:9093

# 알림 규칙 로드
rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

# 스크래핑 설정
scrape_configs:
  # AI 서버 모니터링
  - job_name: 'ai-server'
    metrics_path: '/metrics'
    static_configs:
      - targets: ['ai-server:8000']
        labels:
          service: 'ai-image-analysis'
          environment: 'production'

  # 프로메테우스 자체 모니터링
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # cAdvisor를 통한 컨테이너 모니터링 (선택사항)
  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']

  # 노드 익스포터를 통한 호스트 모니터링 (선택사항)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']